name: 'Setup Rust'
description: 'Setup Rust using Rustup'
inputs:
  version:
    description: 'Rust version to use. By default latest stable version'
    required: false
    default: 'stable'
  component:
    description: 'Rust extra component to install like clippy'
    required: false
  target:
    description: 'Rust extra target to install like wasm32-unknown-unknown'
    required: false
  cache-key:
    description: 'Extra cache key to use'
    required: false
    default: ''
runs:
  using: "composite"
  steps:
    - run: which rustup || sudo DEBIAN_FRONTEND=noninteractive apt-get -y install rustup
      shell: bash
      if: runner.os == 'Linux'
    - run: rustup default ${{ inputs.version }}
      shell: bash
    - run: rustup component add ${{ inputs.component }}
      shell: bash
      if: ${{ inputs.component }}
    - run: rustup target add ${{ inputs.target }}
      shell: bash
      if: ${{ inputs.target }}
    - uses: Swatinem/rust-cache@v2
      continue-on-error: true
      with:
        cache-all-crates: true
        cache-on-failure: true
        key: ${{ inputs.cache-key }}
        save-if: ${{ github.ref == 'refs/heads/main' }}
        workspaces: |
          . -> target
          fuzz -> target
