version: 2

sphinx:
  builder: html
  configuration: python/docs/conf.py

build:
  os: "ubuntu-lts-latest"
  tools:
    python: "3"
    rust: latest
  apt_packages:
    - clang

python:
  install:
    - requirements: python/requirements.dev.txt
    - method: pip
      path: python

submodules:
  include: all
