version: 2

sphinx:
  builder: html
  configuration: python/docs/conf.py

build:
  os: "ubuntu-lts-latest"
  tools:
    python: "3"
  apt_packages:
    - clang
  jobs:
    pre_create_environment:
      - asdf install rust latest
      - asdf global rust latest
      - asdf plugin add uv
      - asdf install uv latest
      - asdf global uv latest
    create_environment:
      - cd python && uv venv "${READTHEDOCS_VIRTUALENV_PATH}"
    install:
      - cd python && UV_PROJECT_ENVIRONMENT="${READTHEDOCS_VIRTUALENV_PATH}" uv sync --frozen

submodules:
  include: all
