version: 2

sphinx:
  builder: html
  configuration: python/docs/conf.py

build:
  os: "ubuntu-lts-latest"
  tools:
    python: "3"
    rust: latest
  apt_packages:
    - clang
  jobs:
    create_environment:
      - asdf plugin add uv
      - asdf install uv latest
      - asdf global uv latest
      - cd python && UV_PROJECT_ENVIRONMENT=$READTHEDOCS_VIRTUALENV_PATH uv sync --locked
    install:
      - "true"

submodules:
  include: all
