PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX dawgt: <http://www.w3.org/2001/sw/DataAccess/tests/test-dawg#>
PREFIX mf: <http://www.w3.org/2001/sw/DataAccess/tests/test-manifest#>
PREFIX qt: <http://www.w3.org/2001/sw/DataAccess/tests/test-query#>
PREFIX : <http://www.w3.org/2001/sw/DataAccess/tests/data-r2/type-promotion/manifest#>

# List of tests that use named graphs and need to be ignored for HDT,
# which does not support named graphs.
SELECT ?test ?query ?data ?result
WHERE {
  ?test mf:action ?test_action .
  ?test_action qt:query ?query .
  ?test_action qt:data ?data .
  ?test mf:result ?result .
}
ORDER BY ?test
