PREFIX geo: <http://www.opengis.net/ont/geosparql#>
PREFIX geof: <http://www.opengis.net/def/function/geosparql/>

SELECT (geof:sfEquals(geof:union("Polygon((0 0, 2 0, 2 2, 0 2, 0 0))"^^geo:wktLiteral, "Polygon((1 1, 3 1, 3 3, 1 3, 1 1))"^^geo:wktLiteral), "Polygon((0 0, 2 0, 2 1, 3 1, 3 3, 1 3, 1 2, 0 2, 0 0))"^^geo:wktLiteral) AS ?result) WHERE {}
