[build]
rustflags = [
    "-Wtrivial-casts",
    "-Wtrivial-numeric-casts",
    "-Wunsafe-code",
    "-Wunused-lifetimes",
    "-Wunused-qualifications",
    # TODO: 1.63+ "-Wclippy::as-underscore",
    # TODO: 1.65+ ""-Wclippy::bool-to-int-with-if",
    "-Wclippy::borrow-as-ptr",
    "-Wclippy::case-sensitive-file-extension-comparisons",
    "-Wclippy::cast-lossless",
    "-Wclippy::cast-possible-truncation",
    "-Wclippy::cast-possible-wrap",
    "-Wclippy::cast-precision-loss",
    "-Wclippy::cast-ptr-alignment",
    "-Wclippy::cast-sign-loss",
    "-Wclippy::checked-conversions",
    "-Wclippy::clone-on-ref-ptr",
    "-Wclippy::cloned-instead-of-copied",
    "-Wclippy::copy-iterator",
    "-Wclippy::dbg-macro",
    "-Wclippy::decimal-literal-representation",
    "-Wclippy::default-trait-access",
    "-Wclippy::default-union-representation",
    # TODO: 1.61+ "-Wclippy::deref-by-slicing",
    # TODO: 1.63+ "-Wclippy::doc-link-with-quotes",
    # TODO: 1.62+ "-Wclippy::empty-drop",
    "-Wclippy::empty-enum",
    # TODO: on major version "-Wclippy::empty-structs-with-brackets",
    "-Wclippy::enum-glob-use",
    "-Wclippy::exit",
    "-Wclippy::expect-used",
    "-Wclippy::expl-impl-clone-on-copy",
    "-Wclippy::explicit-deref-methods",
    "-Wclippy::explicit-into-iter-loop",
    "-Wclippy::explicit-iter-loop",
    "-Wclippy::filter-map-next",
    "-Wclippy::flat-map-option",
    "-Wclippy::fn-to-numeric-cast-any",
    # TODO: 1.62+ "-Wclippy::format-push-string",
    "-Wclippy::from-iter-instead-of-collect",
    "-Wclippy::get-unwrap",
    "-Wclippy::if-not-else",
    "-Wclippy::if-then-some-else-none",
    "-Wclippy::implicit-clone",
    "-Wclippy::inconsistent-struct-constructor",
    "-Wclippy::index-refutable-slice",
    "-Wclippy::inefficient-to-string",
    "-Wclippy::inline-always",
    "-Wclippy::inline-asm-x86-att-syntax",
    "-Wclippy::inline-asm-x86-intel-syntax",
    "-Wclippy::invalid-upcast-comparisons",
    "-Wclippy::items-after-statements",
    "-Wclippy::large-digit-groups",
    # TODO: 1.68+ "-Wclippy::large-futures",
    "-Wclippy::large-stack-arrays",
    "-Wclippy::large-types-passed-by-value",
    "-Wclippy::let-underscore-must-use",
    "-Wclippy::let-unit-value",
    "-Wclippy::linkedlist",
    "-Wclippy::lossy-float-literal",
    "-Wclippy::macro-use-imports",
    "-Wclippy::manual-assert",
    # TODO: 1.65+ "-Wclippy::manual-instant-elapsed",
    # TODO: 1.67+ "-Wclippy::manual-let-else",
    "-Wclippy::manual-ok-or",
    # TODO: 1.65+ "-Wclippy::manual-string-new",
    "-Wclippy::many-single-char-names",
    "-Wclippy::map-unwrap-or",
    "-Wclippy::match-bool",
    "-Wclippy::match-same-arms",
    "-Wclippy::match-wildcard-for-single-variants",
    "-Wclippy::maybe-infinite-iter",
    "-Wclippy::mem-forget",
    # TODO: 1.63+ "-Wclippy::mismatching-type-param-order",
    "-Wclippy::multiple-inherent-impl",
    "-Wclippy::mut-mut",
    "-Wclippy::mutex-atomic",
    "-Wclippy::naive-bytecount",
    "-Wclippy::needless-bitwise-bool",
    "-Wclippy::needless-continue",
    "-Wclippy::needless-pass-by-value",
    "-Wclippy::no-effect-underscore-binding",
    # TODO: 1.69+ "-Wclippy::no-mangle-with-rust-abi",
    "-Wclippy::non-ascii-literal",
    "-Wclippy::print-stderr",
    "-Wclippy::print-stdout",
    "-Wclippy::ptr-as-ptr",
    "-Wclippy::range-minus-one",
    "-Wclippy::range-plus-one",
    "-Wclippy::rc-buffer",
    "-Wclippy::rc-mutex",
    "-Wclippy::redundant-closure-for-method-calls",
    "-Wclippy::redundant-else",
    "-Wclippy::redundant-feature-names",
    "-Wclippy::ref-binding-to-reference",
    "-Wclippy::ref-option-ref",
    "-Wclippy::rest-pat-in-fully-bound-structs",
    "-Wclippy::return-self-not-must-use",
    "-Wclippy::same-functions-in-if-condition",
    # TODO: strange failure on 1.60 "-Wclippy::same-name-method",
    # TODO: 1.68+ "-Wclippy::semicolon-outside-block",
    "-Wclippy::single-match-else",
    "-Wclippy::stable-sort-primitive",
    "-Wclippy::str-to-string",
    "-Wclippy::string-add",
    "-Wclippy::string-add-assign",
    "-Wclippy::string-lit-as-bytes",
    "-Wclippy::string-to-string",
    # TODO: 1.67+ "-Wclippy::suspicious-xor-used-as-pow",
    "-Wclippy::todo",
    "-Wclippy::transmute-ptr-to-ptr",
    "-Wclippy::trivially-copy-pass-by-ref",
    "-Wclippy::try-err",
    "-Wclippy::unicode-not-nfc",
    "-Wclippy::unimplemented",
    # TODO: 1.66+ "-Wclippy::uninlined-format-args",
    # TODO: 1.70+ "-Wclippy::unnecessary-box-returns",
    # TODO: 1.61+ "-Wclippy::unnecessary-join",
    # TODO: 1.67+ "-Wclippy::unnecessary-safety-comment",
    # TODO: 1.67+ "-Wclippy::unnecessary-safety-doc",
    "-Wclippy::unnecessary-self-imports",
    "-Wclippy::unnecessary-wraps",
    "-Wclippy::unneeded-field-pattern",
    "-Wclippy::unnested-or-patterns",
    "-Wclippy::unreadable-literal",
    "-Wclippy::unseparated-literal-suffix",
    "-Wclippy::unused-async",
    "-Wclippy::unused-self",
    "-Wclippy::use-debug",
    "-Wclippy::used-underscore-binding",
    "-Wclippy::verbose-bit-mask",
    "-Wclippy::verbose-file-reads",
    "-Wclippy::wildcard-dependencies",
    "-Wclippy::zero-sized-map-values",
]