[build]
rustflags = [
    "-Wtrivial-casts",
    "-Wtrivial-numeric-casts",
    "-Wunsafe_code",
    "-Wunused-lifetimes",
    "-Wunused-qualifications",
    "-Wclippy::cast-lossless",
    "-Wclippy::cast-possible-truncation",
    "-Wclippy::cast-possible-wrap",
    "-Wclippy::cast-precision-loss",
    "-Wclippy::cast-sign-loss",
    "-Wclippy::checked-conversions",
    "-Wclippy::cloned-instead-of-copied",
    "-Wclippy::copy-iterator",
    "-Wclippy::dbg-macro",
    "-Wclippy::debug-assert-with-mut-call",
    "-Wclippy::decimal-literal-representation",
    "-Wclippy::empty-line-after-outer-attr",
    "-Wclippy::empty-enum",
    "-Wclippy::enum-glob-use",
    "-Wclippy::expect-used",
    "-Wclippy::expl-impl-clone-on-copy",
    "-Wclippy::explicit-deref-methods",
    "-Wclippy::explicit-into-iter-loop",
    "-Wclippy::explicit-iter-loop",
    "-Wclippy::fallible-impl-from",
    "-Wclippy::filter-map-next",
    "-Wclippy::flat-map-option",
    "-Wclippy::from-iter-instead-of-collect",
    "-Wclippy::get-unwrap",
    "-Wclippy::if-not-else",
    "-Wclippy::implicit-clone",
    "-Wclippy::implicit-saturating-sub",
    "-Wclippy::imprecise-flops",
    "-Wclippy::inconsistent-struct-constructor",
    "-Wclippy::inefficient-to-string",
    "-Wclippy::inline-always",
    "-Wclippy::invalid-upcast-comparisons",
    "-Wclippy::items-after-statements",
    "-Wclippy::large-digit-groups",
    "-Wclippy::large-stack-arrays",
    "-Wclippy::large-types-passed-by-value",
    "-Wclippy::let-underscore-must-use",
    "-Wclippy::let-unit-value",
    "-Wclippy::linkedlist",
    "-Wclippy::macro-use-imports",
    "-Wclippy::manual-ok-or",
    "-Wclippy::map-flatten",
    "-Wclippy::map-unwrap-or",
    "-Wclippy::match-bool",
    "-Wclippy::match-same-arms",
    "-Wclippy::match-wildcard-for-single-variants",
    "-Wclippy::maybe-infinite-iter",
    "-Wclippy::mem-forget",
    "-Wclippy::multiple-inherent-impl",
    "-Wclippy::mut-mut",
    "-Wclippy::mutex-integer",
    "-Wclippy::naive-bytecount",
    "-Wclippy::needless-bitwise-bool",
    "-Wclippy::needless-continue",
    "-Wclippy::needless-pass-by-value",
    "-Wclippy::non-ascii-literal",
    "-Wclippy::nonstandard-macro-braces",
    "-Wclippy::path-buf-push-overwrite",
    "-Wclippy::print-stderr",
    "-Wclippy::print-stdout",
    "-Wclippy::range-minus-one",
    "-Wclippy::range-plus-one",
    "-Wclippy::rc-mutex",
    "-Wclippy::enum-variant-names",
    "-Wclippy::redundant-else",
    "-Wclippy::redundant-pub-crate",
    "-Wclippy::ref-binding-to-reference",
    "-Wclippy::ref-option-ref",
    "-Wclippy::rest-pat-in-fully-bound-structs",
    "-Wclippy::same-functions-in-if-condition",
    "-Wclippy::str-to-string",
    "-Wclippy::string-add",
    "-Wclippy::string-add-assign",
    "-Wclippy::string-lit-as-bytes",
    "-Wclippy::string-to-string",
    "-Wclippy::suboptimal-flops",
    "-Wclippy::suspicious-operation-groupings",
    "-Wclippy::todo",
    "-Wclippy::trait-duplication-in-bounds",
    "-Wclippy::transmute-ptr-to-ptr",
    "-Wclippy::trivial-regex",
    "-Wclippy::trivially-copy-pass-by-ref",
    "-Wclippy::type-repetition-in-bounds",
    "-Wclippy::unicode-not-nfc",
    "-Wclippy::unimplemented",
    "-Wclippy::unnecessary-self-imports",
    "-Wclippy::unnecessary-wraps",
    "-Wclippy::unneeded-field-pattern",
    "-Wclippy::unnested-or-patterns",
    "-Wclippy::unreadable-literal",
    "-Wclippy::unseparated-literal-suffix",
    "-Wclippy::unused-async",
    "-Wclippy::unused-self",
    "-Wclippy::use-debug",
    "-Wclippy::use-self",
    "-Wclippy::used-underscore-binding",
    "-Wclippy::useless-let-if-seq",
    "-Wclippy::useless-transmute",
    "-Wclippy::verbose-bit-mask",
    "-Wclippy::verbose-file-reads",
    "-Wclippy::wildcard-dependencies",
    "-Wclippy::zero-sized-map-values",
    "-Wclippy::wrong-self-convention",
]